run:
  timeout: 5m
issues:
  fix: true
linters:
  enable-all: true
  disable:
  - nestif
  - gochecknoglobals
  - funlen
  - gocognit
  - exhaustivestruct
  - cyclop
  # https://github.com/tomarrell/wrapcheck/issues/8
  - wrapcheck
  - varnamelen