run:
  timeout: 5m
issues:
  fix: true
linters:
  enable-all: true
  disable:
  - nestif
  - gochecknoglobals
  - funlen
  - gocognit
  - exhaustivestruct
  - exhaustruct
  - cyclop
  # https://github.com/tomarrell/wrapcheck/issues/8
  - wrapcheck
  - varnamelen
  - nosnakecase
  - musttag
  - depguard
  # deprecated
  - deadcode
  - copyloopvar
  - golint
  - ifshort
  - interfacer
  - intrange
  - maligned
  - scopelint
  - structcheck
  - varcheck