version: '3'

services:
  envoy-control-plane:
    hostname: envoy-control-plane
    build:
      context: .
    volumes:
    - .:/app:ro
    environment:
    #- GODEBUG=http2debug=2
    - MY_POD_NAMESPACE=default
    ports:
    - 127.0.0.1:18081:18081
    command:
    - -log.level=INFO
    - -log.pretty
    - -kubeconfig.path=/app/kubeconfig
    - -ssl.crt=certs/CA.crt
    - -ssl.key=certs/CA.key
    - -web.adminUser=admin
    - -web.adminPassword=admin
    - -leaderElection=false
    #- -ssl.no-validation
  statsd:
    image: prom/statsd-exporter:v0.18.0
    ports:
    - 127.0.0.1:9102:9102
  redis:
    image: redis:alpine
  ratelimit:
    image: envoyproxy/ratelimit:6f5de117
    depends_on:
    - redis
    volumes:
    - ./config:/data:ro
    environment:
    - USE_STATSD=true
    - STATSD_HOST=statsd
    - STATSD_PORT=9125
    - LOG_LEVEL=error
    - REDIS_SOCKET_TYPE=tcp
    - REDIS_URL=redis:6379
    - RUNTIME_ROOT=/data
    - RUNTIME_SUBDIRECTORY=ratelimit
    command:
    - /bin/sh
    - -c
    - |
      set -ex
      while ! nc -z redis 6379; do
        echo wait for redis...
        sleep 1
      done
      ratelimit
  envoy-test1:
    build:
      dockerfile: ./envoy/Dockerfile
      context: .
    ports:
    - 127.0.0.1:8000:8000   # inbound
    - 127.0.0.1:18000:18000 # admin
    volumes:
    - ./envoy/envoy.defaults/envoy.yaml:/envoy/envoy.yaml:ro
    - ./certs/:/certs:ro
    environment:
    - ENVOY_SERVICE_NAME=test1-id
    - JAEGER_AGENT_HOST=jaeger
    command:
    - /bin/sh
    - -c
    - |
      zone="us-east-1b"
      #zone=$$(cli)

      /usr/local/bin/envoy \
      --config-path /etc/envoy/envoy.yaml \
      --log-level warn \
      --service-cluster test \
      --service-node test1-id \
      --drain-time-s 10 \
      --service-zone $$zone
  local-service-a:
    hostname: local-service-a
    build:
      dockerfile: ./envoy/Dockerfile
      context: .
    environment:
    - ENVOY_SERVICE_NAME=test2-id
    - JAEGER_AGENT_HOST=jaeger
    command:
    - /usr/local/bin/envoy
    - --config-path /etc/envoy/envoy.yaml
    - --service-cluster test
    - --service-node test2-id
    - --log-level warn
    volumes:
    - ./envoy/envoy.defaults/envoy.yaml:/envoy/envoy.yaml:ro
    - ./certs/:/certs:ro
    ports:
    - 127.0.0.1:8001:8001 # service
    - 127.0.0.1:18001:18000 # admin
  local-service-b:
    hostname: local-service-b
    build:
      dockerfile: ./envoy/Dockerfile
      context: .
    environment:
    - ENVOY_SERVICE_NAME=test2-id
    - JAEGER_AGENT_HOST=jaeger
    command:
    - /usr/local/bin/envoy
    - --config-path /etc/envoy/envoy.yaml
    - --service-cluster test
    - --service-node test3-id
    - --log-level warn
    volumes:
    - ./envoy/envoy.defaults/envoy.yaml:/envoy/envoy.yaml:ro
    - ./certs/:/certs:ro
    ports:
    - 127.0.0.1:8002:8001 # service
    - 127.0.0.1:18002:18000 # admin
  jaeger:
    image: jaegertracing/all-in-one:1.20
    command:
    - --log-level=warn
    environment:
    - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
    - 127.0.0.1:16686:16686