version: '3'

services:
  envoy-control-plane:
    image: alpine:3.13
    volumes:
    - .:/app
    environment:
    - MY_POD_NAMESPACE=default
    ports:
    - 18081:18081
    command:
    - /app/main-linux
    - -log.level=INFO
    - -kubeconfig.path=/app/kubeconfig
  statsd:
    image: prom/statsd-exporter:v0.18.0
    ports:
    - 9102:9102
  redis:
    image: redis:alpine
  ratelimit:
    image: envoyproxy/ratelimit:6f5de117
    depends_on:
    - redis
    volumes:
    - ./config:/data
    environment:
    - USE_STATSD=true
    - STATSD_HOST=statsd
    - STATSD_PORT=9125
    - LOG_LEVEL=error
    - REDIS_SOCKET_TYPE=tcp
    - REDIS_URL=redis:6379
    - RUNTIME_ROOT=/data
    - RUNTIME_SUBDIRECTORY=ratelimit
    command:
    - /bin/sh
    - -c
    - |
      set -ex
      while ! nc -z redis 6379; do
        echo wait for redis...
        sleep 1
      done
      ratelimit
  envoy-test1:
    build:
      context: ./envoy
    ports:
    - 8000:8000   # inbound
    - 18000:18000 # admin
    volumes:
    - ./envoy/envoy.defaults/envoy.yaml:/envoy/envoy.yaml
    - .:/src
    environment:
    - ENVOY_SERVICE_NAME=test-envoy-service
    - JAEGER_AGENT_HOST=jaeger
    command:
    - /bin/sh
    - -c
    - |
      zone="us-east-1b"
      #zone=$$(cli)

      /usr/local/bin/envoy \
      --config-path /etc/envoy/envoy.yaml \
      --log-level warn \
      --bootstrap-version 3 \
      --service-cluster test \
      --service-node test1-id \
      --drain-time-s 10 \
      --service-zone $$zone
  local-service-a:
    hostname: local-service-a
    image: envoyproxy/envoy:v1.18.3
    command:
    - /usr/local/bin/envoy 
    - --config-path /etc/envoy/envoy.yaml
    - --log-level warn
    volumes:
    - ./config/mock/:/etc/envoy/
    ports:
    - 8001:8001 # service
    - 18001:18000 # admin
  local-service-b:
    hostname: local-service-a
    image: envoyproxy/envoy:v1.18.3
    command:
    - /usr/local/bin/envoy 
    - --config-path /etc/envoy/envoy.yaml
    - --log-level warn
    volumes:
    - ./config/mock/:/etc/envoy/
    ports:
    - 8002:8001 # service
    - 18002:18000 # admin
  jaeger:
    image: jaegertracing/all-in-one:1.20
    command:
    - --log-level=warn
    environment:
    - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
    - "16686:16686"