version: '3'

services:
  redis:
    image: redis:alpine
  ratelimit:
    image: envoyproxy/ratelimit:v1.4.0
    depends_on:
    - redis
    volumes:
    - ./config:/data
    environment:
    - USE_STATSD=false
    - LOG_LEVEL=error
    - REDIS_SOCKET_TYPE=tcp
    - REDIS_URL=redis:6379
    - RUNTIME_ROOT=/data
    - RUNTIME_SUBDIRECTORY=ratelimit
    command:
    - /bin/sh
    - -c
    - |
      set -ex
      while ! nc -z redis 6379; do
        echo wait for redis...
        sleep 1
      done
      ratelimit
  envoy-test1:
    build:
      context: ./envoy
    ports:
    - 8000:8000   # inbound
    - 18000:18000 # admin
    volumes:
    - ./envoy/envoy.defaults/envoy.yaml:/envoy/envoy.yaml
    environment:
    - ENVOY_SERVICE_NAME=test-envoy-service
    - JAEGER_AGENT_HOST=jaeger
    command:
    - /bin/sh
    - -c
    - |
      zone="us-east-1b"
      #zone=$$(cli)

      /usr/local/bin/envoy \
      --config-path /etc/envoy/envoy.yaml \
      --log-level warn \
      --bootstrap-version 3 \
      --service-cluster test \
      --service-node test1-id \
      --service-zone $$zone
  nginxdemo-a:
    hostname: nginxdemo-a
    image: nginxdemos/hello:plain-text
  nginxdemo-b:
    hostname: nginxdemo-b
    image: nginxdemos/hello:plain-text
  jaeger:
    image: jaegertracing/all-in-one
    environment:
    - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
    - "16686:16686"