version: '3'

services:
  envoy-test1:
    build:
      context: ./envoy
    ports:
    - 8000:8000
    - 8001:8001
    volumes:
    - ./envoy/envoy.defaults/envoy.yaml:/envoy/envoy.yaml
    environment:
    - ENVOY_SERVICE_NAME=test-envoy-service
    - JAEGER_AGENT_HOST=jaeger
    command:
    - /bin/sh
    - -c
    - |
      zone="us-east-1b"
      #zone=$$(cli)

      /usr/local/bin/envoy \
      --config-path /etc/envoy/envoy.yaml \
      --log-level warn \
      --service-cluster test \
      --service-node test1-id \
      --service-zone $$zone
  nginxdemo-a:
    hostname: nginxdemo-a
    image: nginxdemos/hello:plain-text
  nginxdemo-b:
    hostname: nginxdemo-b
    image: nginxdemos/hello:plain-text
  jaeger:
    image: jaegertracing/all-in-one
    environment:
    - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
    - "16686:16686"