kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app: envoy-control-plane
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app: envoy-control-plane
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: envoy-control-plane
  namespace: {{ .Release.Namespace }}