apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: envoy-control-plane-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envoy-control-plane
roleRef:
  kind: Role
  name: envoy-control-plane-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: envoy-control-plane
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: envoy-control-plane-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: envoy-control-plane
roleRef:
  kind: ClusterRole
  name: envoy-control-plane-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: envoy-control-plane
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-control-plane
  labels:
    app: envoy-control-plane
spec:
  selector:
    matchLabels:
      app: envoy-control-plane
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      annotations:
        prometheus.io/path: '/api/metrics'
        prometheus.io/scrape: 'true'
        prometheus.io/port: '18082'
      labels:
        app: envoy-control-plane
    spec:
      serviceAccountName: envoy-control-plane
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - envoy-control-plane
            topologyKey: kubernetes.io/hostname
      volumes:
      - name: certs
        configMap:
          name: envoy-control-plane-certs
      containers:
      - name: envoy-control-plane
        image: {{ tpl .Values.registry.image . | quote }}
        imagePullPolicy: {{ .Values.registry.imagePullPolicy | quote }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 30001
          runAsGroup: 30001
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        command:
        - /app/envoy-control-plane
        - -ssl.crt=/certs/CA.crt
        - -ssl.key=/certs/CA.key
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /api/metrics
            port: 18082
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 18080
        - containerPort: 18081
        - containerPort: 18082
        volumeMounts:
        - name: certs
          mountPath: /certs
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-control-plane
  labels:
    app: envoy-control-plane
spec:
  type: ClusterIP
  clusterIP: "None" # headless service
  ports:
  - name: xds
    port: 18080
    protocol: TCP
  - name: https
    port: 18081
    protocol: TCP
  selector:
    app: envoy-control-plane
{{ if .Values.service.external.enable }}
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-control-plane-external
  labels:
    app: envoy-control-plane
spec:
  type: {{ .Values.service.external.type }}
  ports:
  - name: xds
    port: 18080
    targetPort: 18080
    protocol: TCP
  selector:
    app: envoy-control-plane
{{ end }}