apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-certs
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-99"
data:
  CA.crt: |
{{- .Values.caCrt | nindent 5 }}
  envoy.crt: |
{{- .Values.envoyCrt | nindent 5 }}
  envoy.key: |
{{- .Values.envoyKey | nindent 5 }}
  egress.crt: |
{{- .Values.egressCrt | nindent 5 }}
  egress.key: |
{{- .Values.egressKey | nindent 5 }}