{{ if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: envoy-ratelimit
spec:
{{ toYaml .Values.pdb.spec | nindent 2 }}
  selector:
    matchLabels:
      app: envoy-ratelimit
{{ end }}