apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-control-plane
  labels:
    app: envoy-control-plane
spec:
  selector:
    matchLabels:
      app: envoy-control-plane
  replicas: 1
  template:
    metadata:
      labels:
        app: envoy-control-plane
    spec:
      serviceAccountName: envoy-control-plane
      containers:
      - name: envoy-control-plane
        image: {{ .Values.registry.image | quote }}
        imagePullPolicy: {{ .Values.registry.imagePullPolicy | quote }}
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        command:
        - /app/envoy-control-plane
        - --log.json
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        ports:
        - containerPort: 18080
        - containerPort: 18081
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-control-plane
  labels:
    app: envoy-control-plane
spec:
  type: ClusterIP
  ports:
  - name: xds
    port: 18080
    protocol: TCP
  - name: http
    port: 18081
    protocol: TCP
  selector:
    app: envoy-control-plane