apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  labels:
    app: envoy
spec:
  selector:
    matchLabels:
      app: envoy
  replicas: 2
  template:
    metadata:
      labels:
        app: envoy
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - envoy
            topologyKey: topology.kubernetes.io/zone
      containers:
      - name: envoy
        image: {{ .Values.envoy.registry.image | quote }}
        imagePullPolicy: {{ .Values.envoy.registry.imagePullPolicy | quote }}
        args:
        - /bin/sh
        - -c
        - |
          zone="unknown"
          zone=$(cli)

          /usr/local/bin/envoy \
          --config-path /etc/envoy/envoy.yaml \
          --log-level warn \
          --service-cluster test \
          --service-node test1-id \
          --service-zone $zone
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        env:
        - name: ENVOY_SERVICE_NAME
          value: "test-envoy-service"
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8000
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: envoy
  labels:
    app: envoy
spec:
  type: ClusterIP
  ports:
  - name: admin
    port: 8000
    protocol: TCP
  - name: http
    port: 8001
    protocol: TCP
  selector:
    app: envoy