#{{ if .Values.withExamples }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-pod-config
data:
  envoy.yaml: |-
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 18000
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 8001
        traffic_direction: INBOUND
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              codec_type: AUTO
              route_config:
                name: ingress
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    direct_response:
                      status: "200"
                      body:
                        inline_string: "Hello World"
              http_filters:
              - name: envoy.filters.http.router
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-001
  labels:
    app: test-001
spec:
  selector:
    matchLabels:
      app: test-001
  replicas: 2
  template:
    metadata:
      labels:
        app: test-001
    spec:
      volumes:
      - name: config
        configMap:
          name: test-pod-config
      containers:
      - name: test-001
        image: envoyproxy/envoy:v1.19.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 10m
            memory: 100Mi
        # stop container after 30 sec
        # lifecycle:
        #   preStop:
        #     exec:
        #       command:
        #       - /bin/sleep
        #       - "30"
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 3
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /etc/envoy/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-002
  labels:
    app: test-002
spec:
  selector:
    matchLabels:
      app: test-002
  replicas: 2
  template:
    metadata:
      labels:
        app: test-002
    spec:
      volumes:
      - name: config
        configMap:
          name: test-pod-config
      containers:
      - name: test-002
        image: envoyproxy/envoy:v1.19.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 10m
            memory: 100Mi
        # stop container after 30 sec
        # lifecycle:
        #   preStop:
        #     exec:
        #       command:
        #       - /bin/sleep
        #       - "30"
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 3
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /etc/envoy/
#{{ end }}