global:
  metrics:
    enabled: false

metrics:
  enabled: false

# disable tls validation, only for development purposes
# do not enable in production
noTLSValidation: false

tag: v0.3.9

image:
  repository: paskalmaksim/envoy-control-plane
  pullPolicy: IfNotPresent

sidecar:
  image:
    repository: paskalmaksim/envoy-docker-image
    pullPolicy: IfNotPresent

resources: {}

env: []
args: []

# additional certs in configmap
egressCrt: ""
egressKey: ""

# to generate new certs
# mkdir certs && go run github.com/maksim-paskal/envoy-control-plane/cmd/gencerts@latest
# kubectl create configmap helmValues \
# --from-file caCrt=./certs/CA.crt \
# --from-file caKey=./certs/CA.key \
# --from-file envoyCrt=./certs/envoy.crt \
# --from-file envoyKey=./certs/envoy.key \
# --dry-run=client -o yaml

caCrt: |
  -----BEGIN CERTIFICATE-----
  MIIDizCCAnOgAwIBAgIBATANBgkqhkiG9w0BAQsFADBWMQswCQYDVQQGEwJVUzEc
  MBoGA1UEChMTZW52b3ktY29udHJvbC1wbGFuZTELMAkGA1UECxMCQ0ExHDAaBgNV
  BAMTE2Vudm95LWNvbnRyb2wtcGxhbmUwHhcNMjIwNDA3MDQ0NjI4WhcNMzAwNjI0
  MDQ0NjM4WjBWMQswCQYDVQQGEwJVUzEcMBoGA1UEChMTZW52b3ktY29udHJvbC1w
  bGFuZTELMAkGA1UECxMCQ0ExHDAaBgNVBAMTE2Vudm95LWNvbnRyb2wtcGxhbmUw
  ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5TAU7AEDWDXdHR5nlCXOf
  /A6oG20jY2Q1r//MWaja7tu8XzzrZ6HCSAeJFSkw/PnqSOvr8wpVnCa0+E5Zcq2P
  xNbKLSgOTMYRZcTNDTnpvqe6V8Q6UT/a0bKgbGqbONZLu+c9Owyh+IwW0FcuLhDX
  m0LQL4A0FM0NPgTaizQeJUdoELwNUkot5E06zOfaRWVf49MpEqq7sT6y2yl/Modb
  RioGmZ9a8OQheTpI0XRggXyc7KjG0cK7rA/HJPsnfuhqJK8SpOWCLaTrJVlb+Iyw
  P05ASsQawiZqnOTgRmNrcbTnB3sNuOQwFkzenkk4Z0GxODR24DYfvaChK8gycJxj
  AgMBAAGjZDBiMA4GA1UdDwEB/wQEAwIBBjAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
  KwYBBQUHAwIwEgYDVR0TAQH/BAgwBgEB/wIBAjAdBgNVHQ4EFgQU8Y14wFMTKGpE
  QFDYuP/lKVVxfPQwDQYJKoZIhvcNAQELBQADggEBADoi2fSpsXf4PpXmo+tBYHx7
  tuqwEk9G1aRnEqHfmBQe1TQrXcu8vfpd0ILHkZZwYUAmMWi3XeFp36sPleigMLhV
  a0pskDgFOMLZmYirVYzkndbhhwp+B3yOv8ScTKiaWqjeYPVKY8r78C3jz2MTRien
  Itl6ciE+6QYTlNVOIXwyFOA8Yx1o6Cg26N3s1DUEHx68paOZ9pv6hcvq+De4Cuz7
  43jBoPHB8SSPBzM5lGnO4zyspQ9EihL0QjErNmLN+tyYtQHt8bX12y7opI3SAmkI
  dqO62hK/V7fuz1rgwtkFN3LfcDxKS9lnEsu5cJdLdCp3pFTUnl6g48TvVgJDq0k=
  -----END CERTIFICATE-----
caKey: |
  -----BEGIN PRIVATE KEY-----
  MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC5TAU7AEDWDXdH
  R5nlCXOf/A6oG20jY2Q1r//MWaja7tu8XzzrZ6HCSAeJFSkw/PnqSOvr8wpVnCa0
  +E5Zcq2PxNbKLSgOTMYRZcTNDTnpvqe6V8Q6UT/a0bKgbGqbONZLu+c9Owyh+IwW
  0FcuLhDXm0LQL4A0FM0NPgTaizQeJUdoELwNUkot5E06zOfaRWVf49MpEqq7sT6y
  2yl/ModbRioGmZ9a8OQheTpI0XRggXyc7KjG0cK7rA/HJPsnfuhqJK8SpOWCLaTr
  JVlb+IywP05ASsQawiZqnOTgRmNrcbTnB3sNuOQwFkzenkk4Z0GxODR24DYfvaCh
  K8gycJxjAgMBAAECggEBAJMji6+7VsDi9omSkODv7XHoDJdvF+4W+bcsJ9rUg6I+
  NBzUH6LqqueEnP8833W4HJfvCfBWESnEEnR4DHc4+huE+e6Xhww76Lhd8LXHP+qd
  68Cr+vU4GZWgGNEM5maV7o07C7dykWh43n0rOV9BUzxyXM7GOW6h6eYPDnmgOmWI
  aBdl7b8N61xrBHJhNiB7aHoFncZZZfrWMoERGUce/3QXKFVPM3PBQf5EkbDYGmnj
  f+eRHzV09RwwoAenZTbT1oCXIQRD2cblmhiF5olpThYpqvs3alNO0Hd/Pla306J/
  zlZUC7geuCRid3moqGMmj5L39mTQEY4uxQccKxY+NQECgYEA6GnDPoBrm+FQCbcT
  R7RI/kcn8NOtoFKp3p8R8xU3oqDSnoZoApyVwldXAnMy8Y4ZHjrcPXhX3xzl1H9y
  stMw2MGEtp4RinLiHaNwAW2yeVi6acM33Zr17+NXYp3P9Aw55SuN48ZrNsKfHVYh
  +rCHj6aeo5wg+CaDwEG/7Vzj7oECgYEAzBomci/nwZDj5DaFHFNBM+zM06truCU2
  PSPMyD4W8J4amo5eSOGdAZdBrTRZZR/vR1neXg+sAhB84p63BnmT0thvtxKG3Fjs
  eYzNrvHmY8iBJLWS4+2GT/MEpSRP4u/jtCyf3fJpIVVPLvY/OtIKcxe9x3kztQvi
  DE1A9VyEIOMCgYEAvS1BiIF9le+Ld6z2W5pLA/clcqjKnkJLFPOD58pwc8bWScT7
  qoyMdhkjsNHWOLrChVHB7aMkW26pQRPQZ/DxxK2YehEmE/y5QwjC5dbFvHJVojsO
  ISq+X1o8yf/MwkilY33VS/85S+SVIYr3s5e3cF1eqawvRe4LthWOxQWkXoECgYB+
  0uT+4TueML0a6rHNxwHmFQe1o3f85cqNNTijWMmCXIvla/+0Q9T+zxE1YikGSFCz
  wmkFg7F7WulvG/ZYpKUxR+IrHO0F8I+Ie/C2+4MQj9+Hgvgyfz6NYVGKmES3nB6e
  r3frPx0KZGseoE7r6uYpXCBF2c9CeY7N3Bc4H3POxwKBgQDE1ygM7tnnDNL1GknY
  qO2UyxLOf6I3ujugQvbJR8b7aZVrK41b7Y4bOiAJRLsJwa5z01N1IRB9qB5Fg2+c
  KpCao7JpQvfxutX0iGCavB7N/QbMLuUljvsOwIYDWY4eymtyOjbLMNR1dBxFqbNR
  lGdsA7V0kOE0SxzyG+oNHpAnEA==
  -----END PRIVATE KEY-----
envoyCrt: |
  -----BEGIN CERTIFICATE-----
  MIIDhDCCAmygAwIBAgIEYk5srzANBgkqhkiG9w0BAQsFADBWMQswCQYDVQQGEwJV
  UzEcMBoGA1UEChMTZW52b3ktY29udHJvbC1wbGFuZTELMAkGA1UECxMCQ0ExHDAa
  BgNVBAMTE2Vudm95LWNvbnRyb2wtcGxhbmUwHhcNMjIwNDA3MDQ0NjI5WhcNMzAw
  NjI0MDQ0NjM5WjBMMQswCQYDVQQGEwJVUzEcMBoGA1UEChMTZW52b3ktY29udHJv
  bC1wbGFuZTEPMA0GA1UECxMGQ0xJRU5UMQ4wDAYDVQQDEwVlbnZveTCCASIwDQYJ
  KoZIhvcNAQEBBQADggEPADCCAQoCggEBANp+lP+ADR0RkTcLUNB3WfvXfvE/QKWO
  PHPCKmTUFKjNguxwBUejf0Bn/04n7Hj90rnX50lmidWospCJ919H7G4w3CAtaoO/
  H+ExZ5OgG+pbjWxQNqCZMO14mmHqKV1bNa8fIMF0WbwmkBie3VBlqUvta8qvVtt2
  Ok4xH4Ai+OpEWJZSg6GAzcHNJ4fV+5apcObSGerOuw7aeSVoDhc/g9EZtb3kVvdb
  vSo6CNnwawOv0fN2l6f0fQ4uLiRT2HLEA1X34d6thXNlXRchs/+jg7EdnUmDGrVe
  lYpPmaVH1JvYlPvpjb5vWe8G1oOO78hGW2DcxqQAirlrKp/GTRkvWk8CAwEAAaNk
  MGIwDgYDVR0PAQH/BAQDAgeAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
  AjAfBgNVHSMEGDAWgBTxjXjAUxMoakRAUNi4/+UpVXF89DAQBgNVHREECTAHggVl
  bnZveTANBgkqhkiG9w0BAQsFAAOCAQEAkI06AqZfSjWdOMytzSpY0smMfCtHKF/8
  +UZA43Xf0qgHJiWvEsWAidoPUOOoMVPc35jOslXixSg3ZnnBHN+H1qxaetcS7Mac
  Mzw21TjIy08c8wGxVq6G4A9sXMNjDbbROcbzwUYXMJ03jSjT8cnnIhEiUVx47ZOR
  gaPXLQcue9Sg1Uk4mXfSNCfJ5hp0395rYrxo03hp8bU0XHAXKZzKkVqLfSd7wPgq
  x1JH6M+angi14V1oeGYH1Th8wsUJ3IFCs2PoOuSv3hqKcH3SBd/Cf5Zmz61nKEtN
  rrlsPiwqNzZ66zlCphjXWItOIQvMz4B54gxEHl0k8gQPFgShw3Di5Q==
  -----END CERTIFICATE-----
envoyKey: |
  -----BEGIN PRIVATE KEY-----
  MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDafpT/gA0dEZE3
  C1DQd1n7137xP0Cljjxzwipk1BSozYLscAVHo39AZ/9OJ+x4/dK51+dJZonVqLKQ
  ifdfR+xuMNwgLWqDvx/hMWeToBvqW41sUDagmTDteJph6ildWzWvHyDBdFm8JpAY
  nt1QZalL7WvKr1bbdjpOMR+AIvjqRFiWUoOhgM3BzSeH1fuWqXDm0hnqzrsO2nkl
  aA4XP4PRGbW95Fb3W70qOgjZ8GsDr9Hzdpen9H0OLi4kU9hyxANV9+HerYVzZV0X
  IbP/o4OxHZ1Jgxq1XpWKT5mlR9Sb2JT76Y2+b1nvBtaDju/IRltg3MakAIq5ayqf
  xk0ZL1pPAgMBAAECggEBALhukSb62BbpdUKZcqYFmRdUV/scAV2+KpksFMz3mFjE
  4PbjuBE4mXmsT32RhbK7ztzAuqLiwwZvWAtZ6k2rUI/S/nzK2VZMRoS4R039oJK6
  pS4Ap5v4s6xAWVC9cB01mKMyC1xA8l43zvp5Xyc2KSnGR27XguHNcnn+TTDEVIip
  iODbcikKZNNmu56WropVV/johANe9fovF+ssn3TvO1pD/siOM+LjLr/Slf/qZMNF
  mvjhBaJ/s3cWA+kOWc8AavlNCgv6LkcERV9CrfTPf1rC0DdceL6sXsnusSzcg9Au
  XsRkCHNYIVP8qtdUzDq2lE8kU3iAbVfx8WCLVequlsECgYEA4vxDLWCKMOMDuLHw
  aVS2If2G65Sd8xX7Ru8xp06kE2qfSvmildRaezBfmVh8gl8VsXbbPkntrygWTwgL
  V3Tc1wlzGBJ1S19OklGBSM6SJw9LgFQrG6JVlyEiVuk3wxynqukPK9PUMaoZiA03
  RS4+WXC35d3q/Gyz59/HnCpoNSMCgYEA9mx3kvKIJu6BGTfq6mZcb+ezE3p+jlNA
  6/j1dFz0zm04EhSRvHeQq1xcIU5JuGDhNx0TAftEV7JLR5/+TPPcKy4pVLuT4V7l
  iKxXUK/gXSPUD7tY4mfTlZNIAzCwg5xafmdlX7KzpMBwLli6MyMk2fdJQe50vypm
  lf+mLl5zBuUCgYAoF9bl1P+T0wV9QjDs6gGhz15djkq3/VH9HZLvsnxY0aSBYcbO
  IEw7Jjg8pdyYSqNSTWQ8hGJvZe1K2GjoccPwV8L0pY4CWjtOrQbhDVvTemgjqrpS
  j0H/B+NA5sDqvcz/61q6qxf4DcuktHDmz1xEABz7hU9Udv7wHh7r/rGZcQKBgEvD
  8cfWlhISRtMwJCRJsKYfgSm+AedUpaNn+l/6rLJDVngIpv5hbLOjRBhhb70m3FgL
  smprjQnBoe+1u4SBffIw0ThiLAehG8W352jBiqRYfb0QhzWlYqKclAmXEM6GZjRz
  KfIQibdgC53UXfuXFJ+Hrph87pxQNxZrcfbTx14ZAoGBALso5Nhx8K24H4XK51q2
  +Ghqoh8qYyOlTGjoj6D8+db/IG198IJe2aAv4pi0jG1By7U+uuuRR+hZCKY57pP2
  UfEYtqjRICvMq+qsZkb8/irI2mj4l3py/r8o+EALl5KND3LJSM6ZrnpXM1emMJrv
  h+CQP8k3Ey3/gIeh2lEcFYhj
  -----END PRIVATE KEY-----
