withExamples: false

certificates:
  caCrt: |
    -----BEGIN CERTIFICATE-----
    MIIDizCCAnOgAwIBAgIBATANBgkqhkiG9w0BAQsFADBWMQswCQYDVQQGEwJVUzEc
    MBoGA1UEChMTZW52b3ktY29udHJvbC1wbGFuZTELMAkGA1UECxMCQ0ExHDAaBgNV
    BAMTE2Vudm95LWNvbnRyb2wtcGxhbmUwHhcNMjEwODMwMDYwMzQ1WhcNMjkxMTE2
    MDYwMzU1WjBWMQswCQYDVQQGEwJVUzEcMBoGA1UEChMTZW52b3ktY29udHJvbC1w
    bGFuZTELMAkGA1UECxMCQ0ExHDAaBgNVBAMTE2Vudm95LWNvbnRyb2wtcGxhbmUw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDG+JM04ZZiXDM65JFCs37g
    qiqcRyBZ1pGF0Ka8gVrtLy/+nE2cpHvB7lc/SqwmThWB7fVHh9++5hlZ/SqAASjl
    GGu4z6T8mT/eUjngZ7kVvhGld7WiP0OOT4oWWSrNwStX0JPK74DmTMiAXAQ5b+zt
    Nz8rHyAKW7BGTZ5f9gWZA+jnddIyj84IR9l7mvNAR3mRGaiVbqCeE/qvie2O5bmq
    i/qMujAEiBMXv6h5gUBwqufoLT0RQF+aO4AUcgSyLa+lKLYGBzhZbzBbrQndpmZI
    LEx3sjN6CXIWCYjRK5c8gl8E+7ScEehJudLDpBTzQcJffo9Oi9pMNF+wSLBDJsvl
    AgMBAAGjZDBiMA4GA1UdDwEB/wQEAwIBBjAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
    KwYBBQUHAwIwEgYDVR0TAQH/BAgwBgEB/wIBAjAdBgNVHQ4EFgQUWEExN5pUyzkx
    juK6uX2CFsyUvA4wDQYJKoZIhvcNAQELBQADggEBALt5eMKhgbf47WZlBfT2jVXN
    L11joIx7WmEVJ0jP/n9HduXg0RzZE72zhHRiH1/t9jMB5Gg5SLbBC8PuwdPqKAEG
    Tp3X19VDY8nKcgD0Q1hqUdz6Jmy9H1N2sSiutZPoBNpd2nzdw8ZJQgVCM5h2DziR
    QdT/xmKvpCRfvNW3nAUCGyPGB5OkUcU6ZX8QVxeXZ1oNp5LIp59HehSIO98gl3iE
    ITzH/C65ZF3xcVZz+R/KN53PJwxNezRHoWQiFdkIRTGGR8mN/klNNs9nyq9oEd3I
    Qb8C6mI9X3f6CfUb0h0fKyMlW7104+oy9EB8qAJIZuXtXAPpSIMq00gmyfMrhrw=
    -----END CERTIFICATE-----
  caKey: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDG+JM04ZZiXDM6
    5JFCs37gqiqcRyBZ1pGF0Ka8gVrtLy/+nE2cpHvB7lc/SqwmThWB7fVHh9++5hlZ
    /SqAASjlGGu4z6T8mT/eUjngZ7kVvhGld7WiP0OOT4oWWSrNwStX0JPK74DmTMiA
    XAQ5b+ztNz8rHyAKW7BGTZ5f9gWZA+jnddIyj84IR9l7mvNAR3mRGaiVbqCeE/qv
    ie2O5bmqi/qMujAEiBMXv6h5gUBwqufoLT0RQF+aO4AUcgSyLa+lKLYGBzhZbzBb
    rQndpmZILEx3sjN6CXIWCYjRK5c8gl8E+7ScEehJudLDpBTzQcJffo9Oi9pMNF+w
    SLBDJsvlAgMBAAECggEAS9SWvdOv7cK3350W43XnSBZycOcGpFaLVZWExlkCX1zZ
    jM7jIWzqoamFZOC/pUWjGsam8WEOXAHz7YD3/pryjAV3oJK6jW6WkdOCrUy6lFfA
    //AUsEYuKAGWXhgToSEatLgQa4pF9P+Udp8bGQzYHjws/fE509jH4LNaRbZMwdi4
    kmmRWoVs72N7ANSjmIx3Tlk6/4lzlika+lwiFJsc2dve2RJxs7VaoaEvTxaOBJZs
    etSW0jwVoTvYcN3N389P6C9a9w+xclDe6uKQsFyuWXdWibJ/+1coAbCjVljpBrpR
    ZlZdIfnJ0ARXIkcXOfE7ySMJUp3rjS7xzLq2BTa2gQKBgQDeyIpHc6tlFoVeX6IN
    hyTh6nqAJUqVpkYwMp8SAj8FCwiZEjUUbJEGAlOPZg9LCF8708ZeY8djparTcRXW
    f9/lLtS/tYQY3NhidUd/ZlC0TT6YlIoyvzS2e8m3eqlY6I/v+GDcAW2WM9npnKwJ
    hlv4MukqvyUl/Z1QtKRJnrkdoQKBgQDkoyLkK8jQVQ/pTDWxTkDhhTk77LKPVUWF
    /HsNZSM9352xrlPsT7n7RTT8xkSyMLAbDDObEv6BQZMQ2Yk6twrVkUgCgc4iJCS8
    ar4ZrqMKVsmAbLFmVYOTBDDnjxAFHotAYHp2nbUPZPfKVgrRANfqMIgLGLCXOnHi
    Tx5Z6cyfxQKBgERMvvgA4j7vlJvGPexfzlLkjAHVbPRMMaB9JH9k6OUm6M/k4RkN
    37gz5mJEK9QZEPlKh7pQZMSL+b8xIDzOn1mn7dmIUKM+sagdxHmuaHeeZt5oS6Yb
    MJHxiXoSxPBY/CfZwfgxB+PQqbIRMj0JUBDbqthMGZt4EU640tUvMBmBAoGAcVjW
    8VsrgOzKqJQZgj8TNzp+t1CO7TQO9W/H6UocgI4ddXrBLEQSJZmXvUDlyZkNlTsl
    UlnGRnol2JKfz7Xy7xHJK0UC1jYo6Cfa+oxzU6rW1o4MHHmEcxv+yq1H+eG8kzvB
    OpDQtEMP/QVO83KBmB5bM3UYBsD4uIMUvuqDgSkCgYBQ1lcwmDYR7xIJqKDRU+oc
    OMdU6sZaXDOavirw0blqhdFlpsxV1Bc7IjVLfUtgVNVuuo6iVwUoBHJan/6Ly7PH
    RYXoviDt6Tx5dSAneiIr3EKbMJZLodXvImuf411chp1Yu99tFVdPUVywzCaBuigW
    F51XQL9djgI5rkW6nqkepg==
    -----END PRIVATE KEY-----
  envoyCrt: |
    -----BEGIN CERTIFICATE-----
    MIIDhDCCAmygAwIBAgIEYSx0yzANBgkqhkiG9w0BAQsFADBWMQswCQYDVQQGEwJV
    UzEcMBoGA1UEChMTZW52b3ktY29udHJvbC1wbGFuZTELMAkGA1UECxMCQ0ExHDAa
    BgNVBAMTE2Vudm95LWNvbnRyb2wtcGxhbmUwHhcNMjEwODMwMDYwMzQ1WhcNMjkx
    MTE2MDYwMzU1WjBMMQswCQYDVQQGEwJVUzEcMBoGA1UEChMTZW52b3ktY29udHJv
    bC1wbGFuZTEPMA0GA1UECxMGQ0xJRU5UMQ4wDAYDVQQDEwVlbnZveTCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBALi8RtC9m3TzVO7cxuuR1KAllUsLwjKD
    FjisBZb/zbUS6abfLlQ4u56oHl2xAG8FUhFTQ56xerXB25VtzWV0cdINEQolAcku
    ZpDJjURN76thN9QUvJ4O2TIs4dbXwwsxt7MOEactYqQLoCWKXSr4Xe4TQ7mRyvzW
    SMh9v7OHJqIP0FD9VLaCSg2Nxc4bBX8/R/nwnJ+1rwK1RkeW+ybXyT1MByKaFQHe
    nBMYQ10pKHYF4kCaEPmXCLCU+QaqYgBoEHgyGzdJe7/MlCkuN3oCmWZrpz1qpws0
    //Ce8z6f1PZseAyjP9wURWf/k6QBIAWCO6iTKkjP8rL57tm+RfZ6PGUCAwEAAaNk
    MGIwDgYDVR0PAQH/BAQDAgeAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAfBgNVHSMEGDAWgBRYQTE3mlTLOTGO4rq5fYIWzJS8DjAQBgNVHREECTAHggVl
    bnZveTANBgkqhkiG9w0BAQsFAAOCAQEAoA0CLKh/kAru8rmSTqpJVyeTzxK7u9+2
    AHMtyEPFbTIXCdKj6sZA3nM41ydS5VDs0bzWdYRSPkAAcRrv/Jow/VlUBE6t68kc
    4atguv8kgWljsqJy58PBV+YuaJ20pbhKpD7OmHmxughkMCewqR5l074bFzgyaiQO
    LZryQo9TxF7o0uA1qZSXq3QA87GfhV+1vj8DWlSPxJRZjFQDmLvoWCSbCr373MIV
    e96iCna53buzAtiPnEUCJCEInY0RQUNZkjxj8+tDC9uzuD5JvhyEFr71bg4YEmnG
    TwPcsTRRoBJ/TfRmG/tnYSaqPxuupAMhxJso4W18ZC9HFDX3LUkAyw==
    -----END CERTIFICATE-----
  envoyKey: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC4vEbQvZt081Tu
    3MbrkdSgJZVLC8IygxY4rAWW/821Eumm3y5UOLueqB5dsQBvBVIRU0OesXq1wduV
    bc1ldHHSDREKJQHJLmaQyY1ETe+rYTfUFLyeDtkyLOHW18MLMbezDhGnLWKkC6Al
    il0q+F3uE0O5kcr81kjIfb+zhyaiD9BQ/VS2gkoNjcXOGwV/P0f58Jyfta8CtUZH
    lvsm18k9TAcimhUB3pwTGENdKSh2BeJAmhD5lwiwlPkGqmIAaBB4Mhs3SXu/zJQp
    Ljd6Aplma6c9aqcLNP/wnvM+n9T2bHgMoz/cFEVn/5OkASAFgjuokypIz/Ky+e7Z
    vkX2ejxlAgMBAAECggEAfTsM2naeitJlsiMyKgFK3WF86knHVMyuZK6gf3NbdLOk
    dv32fxuSfIRFSYgy3hACSUJjpZF0uP/4pjywL2WXvygic/kQU9xDpUUsobAfl9Mo
    sHl6P7+bFzt7wVO0ocMLX7Na3jSTGNfUsX4xmG6T5k9i6spdi7aL0nYEXWRyGQtt
    PA8QvBwMuH6lSMIkl7Ndh3wRMAwbKu9stsiCjWd6OZ/+WoKlPDza8CKVvQDmwNPU
    yhWNbGrSMfDMTQL1RSLtE6EIl04UPF1IMsJJUoMAnajwsffy1Kq1vHVT8U5m/PDO
    cqNKfKfsGwCwiTQGqwsjeC1efrD9FpJR5sUNZZfKxQKBgQDGa6h61o9+bWEzzq5t
    coZjrG1qMnMAvuyF5MuCoHjrW45mRgECthIlbybm7Xv+JXJItsQ3AnNGzEy05v6h
    SzG+KDSmBnXBzwduYj88BV525+6k1v+71ZSFaz1SNkFnT5iyliWOLWbyQS7Zo46Y
    XbKrr+7pWZJhzFCLwTA0z/AR/wKBgQDuV/nGId06bks6EDULMS4ohG3d8hQzefyC
    mgw/itkBeYXxJnD6p3nKj+Ghfllmk/rp3t9yzEu8+lcbucCWZSCM7Ej3FmLM2AwJ
    lQSdAe+J+YhOn7DZytlbBgYDNNn+GRsH7wn8tRCmeW+SXR/WICamdx5RSZiB3qw+
    ES31D8KpmwKBgCKs28OjzW3dtZf1LZxo4D14+6IMcPaXZwQ7KKmKW7ddx7Pt1e1g
    Xil2lEjVBc8zQhadAgtO/VBJEbqnh6YuWuINaq39AQU+peDPgJd/pLOI8raR8B0m
    RQ9P32aHnsRsL5Y+ERAYtR3u8D4OjDPqY/gHBex3v9Ihf4380+zWzfCHAoGAHASL
    gBcLAotknHa7RY2Kd4jZwXVrmoGEhXXGatHPoLTAYhC6xzxYvM8dHvbTW5OZs1RX
    wA7z+EsVYlT7prJMmURNb35aLupWv+mcmThZCEclFtj+2RtXYbPbkRTta0lYPB6F
    dgdy5Z7w1qvLykgNQxRNpBCatOmQJduvI1eu8nECgYAykiHxeHXBMfgSBPld6j9h
    LNas04xq+lBZm0pHSV8PHsl6j6XmXfMZupjG1+84IrZtuBawZbuDVM2qT93aoESM
    1xda4oxiKYNo432B/vRDnRZoEMpllvqe+Zr17+9zlisTiwYuegysNrQ4r7jJqiSt
    6wC7pddyJdrxVgd8UwavDA==
    -----END PRIVATE KEY-----

registry:
  image: paskalmaksim/envoy-control-plane:v0.3.3
  imagePullPolicy: IfNotPresent

envoy:
  registry:
    image: paskalmaksim/envoy-docker-image:v0.3.3
    imagePullPolicy: IfNotPresent

service:
  external:
    enable: false
    type: LoadBalancer

ratelimit:
  enabled: true
  domain: test
  rate_limits:
  - actions:
    - header_value_match:
        descriptor_value: no-cf-connecting-ip
        expect_match: false
        headers:
        - name: "cf-connecting-ip"
  - actions:
    - request_headers:
        header_name: cf-connecting-ip
        descriptor_key: cf-connecting-ip
  config:
    domain: test
    descriptors:
    - key: remote_address
      rate_limit:
        unit: second
        requests_per_unit: 2
    - key: header_match
      value: no-cf-connecting-ip
      rate_limit:
        unit: minute
        requests_per_unit: 20
    - key: cf-connecting-ip
      rate_limit:
        unit: second
        requests_per_unit: 5
    # black list IP
    - key: cf-connecting-ip
      value: 203.0.113.1
      rate_limit:
        unit: second
        requests_per_unit: 0
    # auto-tests
    - key: cf-connecting-ip
      value: 203.0.113.144
      rate_limit:
        unit: second
        requests_per_unit: 50