apiVersion: v2
icon: https://helm.sh/img/helm.svg
name: envoy-control-plane-examples
version: 0.0.1
description: "Envoy Control Plane test deploy"
maintainers:
- name: maksim-paskal  # Maksim Paskal
  email: paskal.maksim@gmail.com
dependencies:
- name: envoy-control-plane
  version: "*"
  repository: "file://../../charts/envoy-control-plane"
- name: envoy-ratelimit-service
  version: "*"
  repository: "file://../../charts/envoy-ratelimit-service"
