apiVersion: v1
kind: ConfigMap
metadata:
  name: test-envoy
  namespace: default
  labels:
    app: envoy-control-plane
    version: v1
data:
  test1-id: |-
    kubernetes:
    - cluster_name: local_service1
      port: 80
      selector:
        app: test-001

    - cluster_name: test-envoy-service
      port: 80
      selector:
        app: test-002
    endpoints:
    - cluster_name: local_service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 18000
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.2
                port_value: 18000
    listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8000
      traffic_direction: INBOUND
      reuse_port: true
      filter_chains:
      - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            stat_prefix: ingress_http
            codec_type: AUTO
            tracing: {}
            access_log:
            - name: envoy.access_loggers.file
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                path: /dev/stdout
                log_format:
                  json_format:
                    protocol: "%PROTOCOL%"
                    duration: "%DURATION%"
                    response_code: "%RESPONSE_CODE%"
                    response_flags: "%RESPONSE_FLAGS%"
                    x_request_id: "%REQ(X-REQUEST-ID)%"
            rds:
              route_config_name: test
              config_source:
                resource_api_version: V3
                api_config_source:
                  api_type: GRPC
                  transport_api_version: V3
                  grpc_services:
                  - envoy_grpc:
                      cluster_name: xds_cluster
            http_filters:
            - name: envoy.lua
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
                inline_code: |
                  function stringSplit(inputstr, sep)
                    if sep == nil then
                      sep = "%s"
                    end
                    local t={}
                    for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
                      table.insert(t, str)
                    end
                    return t
                  end
                  function envoy_on_request(request_handle)
                    -- cookies to save in metadata
                    local cookiesArray = {"CID"}
                    local cookie = request_handle:headers():get("cookie")
                    local dynamicMetadata = request_handle:streamInfo():dynamicMetadata()

                    if cookie ~= nil then
                      local splitCookieString = stringSplit(cookie, ";")
                      for i, cookieItem in ipairs(splitCookieString) do
                        for y, cookiesItem in ipairs(cookiesArray) do
                          if string.find(cookieItem, cookiesItem) ~= nil then
                            local cookieKV = stringSplit(cookieItem, "=")
                            local cookieName = string.gsub(cookieKV[1], "%s+", "")
                            dynamicMetadata:set("envoy.filters.http.lua.cookie", cookieName, cookieKV[2])
                          end
                        end
                      end
                    end
                  end

            - name: envoy.filters.http.ratelimit
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
                domain: test
                enable_x_ratelimit_headers: DRAFT_VERSION_03
                failure_mode_deny: true
                rate_limit_service:
                  transport_api_version: V3
                  grpc_service:
                    envoy_grpc:
                      cluster_name: rate_limit_cluster
            - name: envoy.filters.http.router
    routes:
    - name: test
      virtual_hosts:
      - name: test
        domains:
        - "*"
        rate_limits:
        - actions:
          - header_value_match:
              descriptor_value: no-cf-connecting-ip
              expect_match: false
              headers:
              - name: "cf-connecting-ip"
        - actions:
          - request_headers:
              header_name: cf-connecting-ip
              descriptor_key: cf-connecting-ip
        routes:
        - match:
            prefix: "/1"
          route:
            cluster: local_service1
        - match:
            prefix: "/2"
          route:
            cluster: local_service2
        - match:
            prefix: "/tls-cluster-example"
          route:
            cluster: tls-cluster-example
        - match:
            prefix: "/aggregate-cluster"
          route:
            cluster: aggregate-cluster
        - match:
            prefix: "/"
          route:
            weighted_clusters:
              clusters:
              - name: local_service1
                weight: 50
              - name: local_service2
                weight: 50
    clusters:
    - name: local_service1
      connect_timeout: 0.25s
      lb_policy: ROUND_ROBIN
      type: EDS
      eds_cluster_config:
        eds_config:
          resource_api_version: V3
          api_config_source:
            api_type: GRPC
            transport_api_version: V3
            grpc_services:
            - envoy_grpc:
                cluster_name: xds_cluster
    - name: local_service2
      connect_timeout: 0.25s
      lb_policy: ROUND_ROBIN
      type: STRICT_DNS
      circuit_breakers:
        thresholds:
        - max_connections: 10
          max_pending_requests: 10
          max_requests: 10
      health_checks:
      - timeout: 1s
        interval: 5s
        unhealthy_threshold: 3
        healthy_threshold: 1
        http_health_check:
          path: "/ready"
      load_assignment:
        cluster_name: local_service2
        endpoints:
        - locality:
            zone: us-east-1a
          lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: nginxdemo-a
                  port_value: 80
        - locality:
            zone: us-east-1b
          lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: nginxdemo-b
                  port_value: 80
    - name: rate_limit_cluster
      connect_timeout: 0.25s
      lb_policy: ROUND_ROBIN
      type: STRICT_DNS
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
      load_assignment:
        cluster_name: rate_limit_cluster
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: ratelimit
                  port_value: 8081
    - name: admin_cluster
      connect_timeout: 0.25s
      lb_policy: ROUND_ROBIN
      type: STATIC
      load_assignment:
        cluster_name: admin_cluster
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 18000
    - name: tls-cluster-example
      connect_timeout: 1s
      type: STATIC
      health_checks:
      - timeout: 1s
        interval: 5s
        unhealthy_threshold: 3
        healthy_threshold: 1
        http_health_check:
          host: "some.com"
          path: "/status.php"
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
      load_assignment:
        cluster_name: tls-cluster-example
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 443
    - name: aggregate-cluster
      connect_timeout: 0.25s
      lb_policy: CLUSTER_PROVIDED
      cluster_type:
        name: envoy.clusters.aggregate
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.clusters.aggregate.v3.ClusterConfig
          clusters:
          - tls-cluster-example
          - local_service2
          - admin_cluster