withExamples: false

registry:
  image: paskalmaksim/envoy-control-plane:latest
  imagePullPolicy: Always

envoy:
  registry:
    image: paskalmaksim/envoy-docker-image:latest
    imagePullPolicy: Always

ratelimit:
  enabled: true
  domain: test
  rate_limits:
  - actions:
    - header_value_match:
        descriptor_value: no-cf-connecting-ip
        expect_match: false
        headers:
        - name: "cf-connecting-ip"
  - actions:
    - request_headers:
        header_name: cf-connecting-ip
        descriptor_key: cf-connecting-ip
  config:
    domain: test
    descriptors:
    - key: remote_address
      rate_limit:
        unit: second
        requests_per_unit: 2
    - key: header_match
      value: no-cf-connecting-ip
      rate_limit:
        unit: minute
        requests_per_unit: 20
    - key: cf-connecting-ip
      rate_limit:
        unit: second
        requests_per_unit: 5
    # black list IP
    - key: cf-connecting-ip
      value: 203.0.113.1
      rate_limit:
        unit: second
        requests_per_unit: 0
    # auto-tests
    - key: cf-connecting-ip
      value: 203.0.113.144
      rate_limit:
        unit: second
        requests_per_unit: 50

ingress:
  enabled: false
  host: test.dev.com