#!/bin/sh

set -ex

docker build . -t envoy-alpine-debug:stack_decode
docker run \
  -it \
  --rm \
  -v $(pwd)/config/:/etc/envoy \
  -p 8000:8000 \
  -p 8001:8001 \
  envoy-alpine-debug:stack_decode \
  /stack_decode.py /usr/local/bin/envoy \
  --config-path /etc/envoy/envoy.yaml \
  --log-level critical \
  --bootstrap-version 3 \
  --service-cluster test \
  --service-node test1-id \
  --service-zone test-zone