apiVersion: v1
kind: Namespace
metadata:
  name: envoy-control-plane
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-control-plane
  namespace: envoy-control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: envoy-control-plane-role
  namespace: envoy-control-plane
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envoy-control-plane
  namespace: envoy-control-plane
roleRef:
  kind: Role
  name: envoy-control-plane-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: envoy-control-plane
  namespace: envoy-control-plane
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-control-plane
  namespace: envoy-control-plane
  labels:
    app: envoy-control-plane
spec:
  selector:
    matchLabels:
      app: envoy-control-plane
  replicas: 1
  template:
    metadata:
      labels:
        app: envoy-control-plane
    spec:
      serviceAccountName: envoy-control-plane
      containers:
      - name: envoy-control-plane
        image: paskalmaksim/envoy-control-plane:dev
        imagePullPolicy: Always
        env:
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        command:
        - /app/envoy-control-plane
        ports:
        - containerPort: 18080
        - containerPort: 18081
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-control-plane
  namespace: envoy-control-plane
  labels:
    app: envoy-control-plane
spec:
  type: ClusterIP
  ports:
  - name: xds
    port: 18080
    protocol: TCP
  - name: http
    port: 18081
    protocol: TCP
  selector:
    app: envoy-control-plane
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: envoy-control-plane
  labels:
    app: envoy-control-plane
    force-update: v2
data:
  test1-id.yaml: |-
    listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
      filter_chains:
      - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
            stat_prefix: ingress_http
            codec_type: AUTO
            tracing:
              provider:
                name: envoy.tracers.dynamic_ot
                typed_config:
                  "@type": type.googleapis.com/envoy.config.trace.v2.DynamicOtConfig
                  library: /usr/local/lib/libjaegertracing_plugin.so
                  config:
                    service_name: front-proxy
                    sampler:
                      type: const
                      param: 1
                    reporter:
                      localAgentHostPort: jaeger:6831
                    headers:
                      jaegerDebugHeader: jaeger-debug-id
                      jaegerBaggageHeader: jaeger-baggage
                      traceBaggageHeaderPrefix: uberctx-
                    baggage_restrictions:
                      denyBaggageOnInitializationFailure: false
                      hostPort: ""
            access_log:
            - name: envoy.access_loggers.file
              typed_config:
                "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
                path: /dev/stdout
                json_format:
                  protocol: "%PROTOCOL%"
                  duration: "%DURATION%"
                  response_code: "%RESPONSE_CODE%"
                  response_flags: "%RESPONSE_FLAGS%"
                  x_request_id: "%REQ(X-REQUEST-ID)%"
            rds:
              route_config_name: test
              config_source:
                api_config_source:
                  api_type: GRPC
                  grpc_services:
                  - envoy_grpc:
                      cluster_name: xds_cluster
            http_filters:
            - name: envoy.filters.http.router
    endpoints:
    - cluster_name: local_service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8000
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.2
                port_value: 8000
    routes:
    - name: test
      virtual_hosts:
      - name: test
        domains:
        - "*"
        routes:
        - match:
            prefix: "/4"
          route:
            cluster: local_service4
        - match:
            prefix: "/1"
          route:
            cluster: local_service1
        - match:
            prefix: "/"
          route:
            weighted_clusters:
              clusters:
              - name: local_service1
                weight: 50
              - name: local_service2
                weight: 50
    clusters:
    - name: local_service1
      connect_timeout: 0.25s
      lb_policy: ROUND_ROBIN
      type: EDS
      eds_cluster_config:
        eds_config:
          api_config_source:
            api_type: GRPC
            grpc_services:
            - envoy_grpc:
                cluster_name: xds_cluster
    - name: local_service2
      connect_timeout: 0.25s
      lb_policy: ROUND_ROBIN
      type: STRICT_DNS
      load_assignment:
        cluster_name: local_service2
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: nginxdemo
                  port_value: 80
    - name: local_service3
      connect_timeout: 0.25s
      lb_policy: ROUND_ROBIN
      type: STRICT_DNS
      load_assignment:
        cluster_name: local_service3
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: nginxdemo
                  port_value: 80
    - name: local_service4
      connect_timeout: 0.25s
      lb_policy: ROUND_ROBIN
      type: STRICT_DNS
      load_assignment:
        cluster_name: local_service3
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: nginxdemo
                  port_value: 80