apiVersion: v1
kind: Namespace
metadata:
  name: envoy-control-plane
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-control-plane
  namespace: envoy-control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: envoy-control-plane-role
  namespace: envoy-control-plane
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envoy-control-plane
  namespace: envoy-control-plane
roleRef:
  kind: Role
  name: envoy-control-plane-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: envoy-control-plane
  namespace: envoy-control-plane
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-control-plane
  namespace: envoy-control-plane
  labels:
    app: envoy-control-plane
spec:
  selector:
    matchLabels:
      app: envoy-control-plane
  replicas: 1
  template:
    metadata:
      labels:
        app: envoy-control-plane
    spec:
      serviceAccountName: envoy-control-plane
      containers:
      - name: envoy-control-plane
        image: paskalmaksim/envoy-control-plane:dev
        imagePullPolicy: Always
        env:
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        command:
        - /app/envoy-control-plane
        ports:
        - containerPort: 18080
        - containerPort: 18081