---
domain: test
descriptors:
- key: remote_address
  rate_limit:
    unit: second
    requests_per_unit: 30
- key: header_match
  value: no-cf-connecting-ip
  rate_limit:
    unit: second
    requests_per_unit: 30
- key: cf-connecting-ip
  rate_limit:
    unit: second
    requests_per_unit: 30
- key: cookie-cid
  rate_limit:
    unit: second
    requests_per_unit: 30
# black list IP
- key: cf-connecting-ip
  value: 203.0.113.1
  rate_limit:
    unit: second
    requests_per_unit: 0
# auto-tests
- key: cf-connecting-ip
  value: 203.0.113.144
  rate_limit:
    unit: second
    requests_per_unit: 50