on:
  push:
    tags:
    - v*
    branches:
    - main
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
      with:
        # https://github.com/tomarrell/wrapcheck/issues/8
        version: v1.38.0