name: test-main
on:
  push:
    # tags:
    #   - v*
    # branches:
    #   - master
    #   - main
  pull_request:
jobs:
  test-main:
    name: Test main package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.15'
    - run: go test -race ./cmd/main