name: test
on:
  push:
    # tags:
    #   - v*
    # branches:
    #   - master
    #   - main
  pull_request:
jobs:
  test:
    name: Test package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.15'
    - run: go mod download
    - run: go mod verify
    - run: go test -race ./cmd/main
    - run: go build -v -o envoy-control-plane ./cmd/main