name: validate-license
on:
  push:
    # tags:
    #   - v*
    # branches:
    #   - master
    #   - main
  pull_request:
jobs:
  validate-license:
    name: validate-license
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check licence in files
      run: ./scripts/validate-license.sh